app/config/urls.py
from django.contrib import admin
from django.urls import path, include
from core.homepage.views import IndexView
from core.login.views import *

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('login/', include('core.login.urls')),
    path('admin/', admin.site.urls),
    path('erp/', include('core.erp.urls')),
    path('reports/', include('core.reports.urls')),
    path('user/', include('core.user.urls')),
    path('report/', include('core.report.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/core/erp/urls.py
from core.erp.views.marca.views import *
from django.urls import path
from core.erp.views.category.views import *
from core.erp.views.client.views import *
from core.erp.views.dashboard.views import *
from core.erp.views.product.views import *
from core.erp.views.sale.views import *
from core.erp.views.tests.views import TestView
from core.erp.views.proveedor.views import *
from core.erp.views.permissions.views import *
from core.erp.views.department.views import *
from core.erp.views.cargos.views import *
from core.erp.views.trabajador.views import *
from core.erp.views.buy.views import *


app_name = 'erp'

urlpatterns = [
    # category
    path('category/list/', CategoryListView.as_view(), name='category_list'),
    path('category/add/', CategoryCreateView.as_view(), name='category_create'),
    path('category/update/<int:pk>/', CategoryUpdateView.as_view(), name='category_update'),
    path('category/delete/<int:pk>/', CategoryDeleteView.as_view(), name='category_delete'),
    # client
    path('client/list/', ClientListView.as_view(), name='client_list'),
    path('client/add/', ClientCreateView.as_view(), name='client_create'),
    path('client/update/<int:pk>/', ClientUpdateView.as_view(), name='client_update'),
    path('client/delete/<int:pk>/', ClientDeleteView.as_view(), name='client_delete'),
    # product
    path('product/list/', ProductListView.as_view(), name='product_list'),
    path('product/add/', ProductCreateView.as_view(), name='product_create'),
    path('product/update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('product/delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),
    # home
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    # test
    path('test/', TestView.as_view(), name='test'),
    # sale
    path('sale/list/', SaleListView.as_view(), name='sale_list'),
    path('sale/add/', SaleCreateView.as_view(), name='sale_create'),
    path('sale/delete/<int:pk>/', SaleDeleteView.as_view(), name='sale_delete'),
    path('sale/update/<int:pk>/', SaleUpdateView.as_view(), name='sale_update'),
    path('sale/invoice/pdf/<int:pk>/', SaleInvoicePDFView.as_view(), name='sale_invoice_pdf'),
    # proveedor
    path('proveedor/list/', ProveedorListView.as_view(), name='proveedor_list'),
    path('proveedor/add/', ProveedorCreateView.as_view(), name='proveedor_create'),
    path('proveedor/update/<int:pk>/', ProveedorUpdateView.as_view(), name='proveedor_update'),
    path('proveedor/delete/<int:pk>/', ProveedorDeleteView.as_view(), name='proveedor_delete'),
    # brand
    path('marca/list/', MarcaListView.as_view(), name='marca_list'),
    path('marca/add/', MarcaCreateView.as_view(), name='marca_create'),
    path('marca/update/<int:pk>/', MarcaUpdateView.as_view(), name='marca_update'),
    path('marca/delete/<int:pk>/', MarcaDeleteView.as_view(), name='marca_delete'),
    #groups
    path('groupgroup/list/', GroupListView.as_view(), name='group_list'),
    path('group/add/', GroupCreateView.as_view(), name='group_create'),
    path('group/update/<int:pk>/',
        GroupUpdateView.as_view(), name='gorup_update'),
    path('group/delete/<int:pk>/', GroupDeleteView.as_view(), name='group_delete'),
    #buy
    path('buy/list/', BuyListView.as_view(), name='buy_list'),
    path('buy/add/', BuyCreateView.as_view(), name='buy_create'),
    path('buy/delete/<int:pk>/', BuyDeleteView.as_view(), name='buy_delete'),
    path('buy/update/<int:pk>/', BuyUpdateView.as_view(), name='buy_update'),
    #path('Buy/expenses/pdf/<int:pk>/', BuyExpensesPDFView.as_view(), name='buy_expenses_pdf'),


]

app/core/erp/views/dashboard/views.py
from datetime import datetime
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Sum
from django.db.models.functions import Coalesce
from django.http import JsonResponse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView, View


from core.erp.models import *
from core.erp.forms import *



class DashboardView(LoginRequiredMixin, TemplateView):
    template_name = 'dashboard.html'

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'get_graph_sales_year_month':
                data = {
                    'name': 'Porcentaje de venta',
                    'showInLegend': False,
                    'colorByPoint': True,
                    'data': self.get_graph_sales_year_month()
                }
            elif action == 'get_graph_sales_products_year_month':
                data = {
                    'name': 'Porcentaje',
                    'colorByPoint': True,
                    'data': self.get_graph_sales_products_year_month(),
                }

            else:
                data['error'] = 'Ha ocurrido un error'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data, safe=False)


    def get_graph_sales_year_month(self):
        data = []
        try:
            year = datetime.now().year
            for m in range(1, 13):
                total = Sale.objects.filter(date_joined__year=year, date_joined__month=m).aggregate(
                    r=Coalesce(Sum('total'), 0)).get('r')
                data.append(float(total))
        except:
            pass
        return data


    def get_graph_sales_products_year_month(self):
        data = []
        year = datetime.now().year
        month = datetime.now().month
        try:
            for p in Product.objects.all():
                total = DetSale.objects.filter(sale__date_joined__year=year, sale__date_joined__month=month, prod_id=p.id).aggregate(
                    r=Coalesce(Sum('subtotal'), 0)).get('r')
                if total > 0:
                    data.append({
                        'name': p.name,
                        'y': float(total)
                    })
        except:
            pass
        return data
    
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['panel'] = 'Panel de administrador'
        context['clients'] = Client.objects.all().count()
        context['stock'] = Product.objects.all().count()
        context['proveedor'] = Proveedor.objects.all().count()
        context['marca'] = Marca.objects.all().count()
        context['sale'] = Sale.objects.all().count()
        context['buy'] = Buy.objects.all().count()
        context['graph_sales_year_month'] = self.get_graph_sales_year_month()
        return context

app/templates/dashboard.html
{% extends 'layout.html' %} {% load static %} {% block head %}
<script src="{% static 'lib/highcharts-8.1.2/highcharts.js' %}"></script>
<script src="{% static 'lib/highcharts-8.1.2/modules/exporting.js' %}"></script>
<script src="{% static 'lib/highcharts-8.1.2/modules/export-data.js' %}"></script>
<script src="{% static 'lib/highcharts-8.1.2/modules/accessibility.js' %}"></script>
{% endblock %} {% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <h2 class="m-0 text-dark"><small>Tablero Principal</small></h2>
            <hr>
            <div class="row">
                <!-- ./col -->
                <div class="col-lg-3 col-6">
                    <!-- small box -->
                    <div class="small-box bg-success">
                        <div class="inner">
                            <h3>{{ clients }}</h3>
                            <p>Clientes</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-stats-bars"></i>
                        </div>
                        <a href="{% url 'erp:client_list' %}" class="small-box-footer">Más Información<i class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <div class="col-lg-3 col-6">
                    <!-- small box -->
                    <div class="small-box bg-info">
                        <div class="inner">
                            <h3>{{ stock }}</h3>
                            <p>Modelos de Repuestos</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-bag"></i>
                        </div>
                        <a href="{% url 'erp:product_list' %}" class="small-box-footer">Más Información<i class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <!-- ./col -->
                <div class="col-lg-3 col-6">
                    <!-- small box -->
                    <div class="small-box bg-warning">
                        <div class="inner">
                            <h3>{{ proveedor }}</h3>
                            <p>Proveedores</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-person-add"></i>
                        </div>
                        <a href="{% url 'erp:proveedor_list' %}" class="small-box-footer">Más Información<i class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <!-- ./col -->
                <div class="col-lg-3 col-6">
                    <!-- small box -->
                    <div class="small-box bg-danger">
                        <div class="inner">
                            <h3>{{ sale }}</h3>
                            <p>Ventas</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-pie-graph"></i>
                        </div>
                        <a href="{% url 'erp:sale_list' %}" class="small-box-footer">Más Información <i class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <!-- ./col -->
                <div class="col-lg-6">
                    <!-- small box -->
                    <div class="small-box bg-secondary">
                        <div class="inner">
                            <h3>{{ marca }}</h3>
                            <p>Marcas</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-pie-graph"></i>
                        </div>
                        <a href="{% url 'erp:marca_list' %}" class="small-box-footer">Más Información<i class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <!-- ./col -->
                <div class="col-lg-6">
                    <!-- small box -->
                    <div class="small-box bg-dark">
                        <div class="inner">
                            <h3>{{ buy }}</h3>
                            <p>Compras</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-pie-graph"></i>
                        </div>
                        <a href="{% url 'erp:buy_list' %}" class="small-box-footer">Más Información <i class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-lg-6">
            <div id="container"></div>
        </div>
        <div class="col-lg-6">
            <div id="container-pie"></div>
        </div>
    </div>
    <br>
    <div class="row">
    </div>
    <br>
</div>
<script type="application/javascript">
    var graphcolumn = Highcharts.chart('container', {
        chart: {
            type: 'column'
        },
        title: {
            text: 'Reporte de Ventas Mensuales'
        },
        subtitle: {
            text: 'Reporte de columnas'
        },
        xAxis: {
            categories: [
                'Enero',
                'Febrero',
                'Marzo',
                'Abril',
                'Mayo',
                'Junio',
                'Julio',
                'Agosto',
                'Septiembre',
                'Octubre',
                'Noviembre',
                'Diciembre'
            ],
            crosshair: true
        },
        yAxis: {
            min: 0,
            title: {
                text: 'Valores $'
            }
        },
        tooltip: {
            headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
            pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                '<td style="padding:0"><b>{point.y:.1f} $</b></td></tr>',
            footerFormat: '</table>',
            shared: true,
            useHTML: true
        },
        plotOptions: {
            column: {
                pointPadding: 0.2,
                borderWidth: 0
            }
        },
    });

    var graphpie = Highcharts.chart('container-pie', {
        chart: {
            plotBackgroundColor: null,
            plotBorderWidth: null,
            plotShadow: false,
            type: 'pie'
        },
        title: {
            text: 'Porcentaje de Ventas por Repuestos'
        },
        tooltip: {
            pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
        },
        accessibility: {
            point: {
                valueSuffix: '%'
            }
        },
        plotOptions: {
            pie: {
                allowPointSelect: true,
                cursor: 'pointer',
                dataLabels: {
                    enabled: true,
                    format: '<b>{point.name}</b>: {point.percentage:.1f} %'
                }
            }
        },
    });

    function get_graph_sales_year_month() {
        $.ajax({
            url: window.location.pathname, //window.location.pathname
            type: 'POST',
            data: {
                'action': 'get_graph_sales_year_month'
            },
            dataType: 'json',
        }).done(function(data) {
            if (!data.hasOwnProperty('error')) {
                graphcolumn.addSeries(data);
                return false;
            }
            message_error(data.error);
        }).fail(function(jqXHR, textStatus, errorThrown) {
            alert(textStatus + ': ' + errorThrown);
        }).always(function(data) {

        });
    }

    function get_graph_sales_products_year_month() {
        $.ajax({
            url: window.location.pathname, //window.location.pathname
            type: 'POST',
            data: {
                'action': 'get_graph_sales_products_year_month'
            },
            dataType: 'json',
        }).done(function(data) {
            if (!data.hasOwnProperty('error')) {
                graphpie.addSeries(data);
                return false;
            }
            message_error(data.error);
        }).fail(function(jqXHR, textStatus, errorThrown) {
            alert(textStatus + ': ' + errorThrown);
        }).always(function(data) {

        });
    }




    $(function() {

        get_graph_sales_year_month();

        get_graph_sales_products_year_month();

    });
</script>
{% endblock %}

app/templates/delete.html
{% extends 'layout.html' %} {% load widget_tweaks %} {% block content %}
<form method="post" action=".">
    <div class="card card-primary">
        <div class="card-header" style="background-color: rgba( 9, 54, 115 );">
            <h3 class="card-title">
                <i class="fas fa-trash"></i> {{ title }}
            </h3>
        </div>
        <div class="card-body">
            {% csrf_token %}
            <input type="hidden" name="action" value="{{ action }}"> {% if form.errors %}
            <div class="alert alert-danger alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
                <h5><i class="icon fas fa-ban"></i> Ha ocurrido un error al querer guardar el registro</h5>
                <ul>
                    {% for field in form %} {% for error in field.errors %}
                    <li>{{ error }}</li>
                    {% endfor %} {% endfor %}
                </ul>
            </div>
            {% endif %}
            <div class="alert alert-danger alert-dismissible">
                <h5><i class="icon fas fa-ban"></i> Notificación!</h5>
                <!--¿Estas seguro de eliminar el registro N°{{ object.name }}?-->
                ¿Está seguro de eliminar este Item?

            </div>
        </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-success btn-flat">
                    <i class="fas fa-save"></i> Si, aceptar
                </button>
            <a href="{{ list_url }}" class="btn btn-danger btn-flat">
                <i class="fas fa-times"></i> Cancelar
            </a>
        </div>
    </div>
</form>
<script>
    $('form').on('submit', function(e) {
        e.preventDefault();
        var parameters = new FormData(this);
        submit_with_ajax(window.location.pathname, 'Notificación', '¿Estas seguro de eliminar el siguiente registro?', parameters, function() {
            Swal.fire({
                title: 'Alerta',
                text: 'Registro Eliminado Correctamente',
                icon: 'success',
                timer: 2000
            }).then((result) => {
                location.href = '{{ list_url }}';
            });

        });
    });
</script>
{% endblock %}

app/templates/footer.html
<!-- Main Footer -->
<footer class="main-footer text-center">
    <strong>Copyright &copy; 2021 <a href="">Lift Servicios</a>.</strong><br> Todos los derechos reservados.
</footer>

app/templates/form.html
{% extends 'layout.html' %}
{% load widget_tweaks %}
{% block head %}
    {% block head_form %}

    {% endblock %}
{% endblock %}
{% block content %}
    <form method="post" action="." enctype="multipart/form-data">
        <div class="card card-primary">
            <div class="card-header" style="background-color: rgba( 9, 54, 115 );">
                <h3 class="card-title">
                    {% if action == 'add' %}
                        <i class="fas fa-plus"></i>
                    {% else %}
                        <i class="fas fa-edit"></i>
                    {% endif %}

                    {{ title }}
                </h3>
            </div>
            <div class="card-body">
                {% csrf_token %}
                <input type="hidden" name="action" value="{{ action }}">
                {% if form.errors %}
                    <div class="alert alert-danger alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <h5><i class="icon fas fa-ban"></i> Ha ocurrido un error al querer guardar el registro</h5>
                        <ul>
                            {% for field in form %}
                                {% for error in field.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
                {% for field in form.visible_fields %}
                    <div class="form-group">
                        <label for="email">{{ field.label }}:</label>
                        {{ field|add_class:'form-control'|attr:'autocomplete:off' }}
                    </div>
                {% endfor %}
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-success btn-flat">
                    <i class="fas fa-save"></i> Guardar registro
                </button>
                <a href="{{ list_url }}" class="btn btn-danger btn-flat">
                    <i class="fas fa-times"></i> Cancelar
                </a>
            </div>
        </div>
    </form>
    <script>
        {% if form.errors %}
            var errors = '';
            {% for field in form %}
                {% for error in field.errors %}
                    errors += '{{ error }}\n';
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                errors += '{{ error }}\n';
            {% endfor %}
            Swal.fire({
                title: 'Error!',
                text: errors,
                icon: 'error'
            });
        {% endif %}

        $('form').on('submit', function (e) {
            e.preventDefault();
            var parameters = new FormData(this);
            submit_with_ajax(window.location.pathname, 'Notificación', '¿Estas seguro de realizar la siguiente acción?', parameters, function () {
                location.href = '{{ list_url }}';
            });
        });
    </script>
{% endblock %}

app/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <link rel="icon" href="{% static 'img/logo.png' %}" type="image/png" />
    <title>{{ title }}</title>
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="{% static 'lib/adminlte-3.0.4/plugins/font-awesome-5.11.1/css/all.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'lib/adminlte-3.0.4/css/adminlte.min.css' %}">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <!-- jQuery -->
    <script src="{% static 'lib/adminlte-3.0.4/plugins/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'lib/adminlte-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'lib/adminlte-3.0.4/js/adminlte.min.js' %}"></script>
    <!-- Sweetalert2 -->
    <script src="{% static 'lib/sweetalert2-9.10.0/sweetalert2.all.min.js' %}"></script>
    <!-- Jquery Confirm -->
    <link rel="stylesheet" href="{% static 'lib/jquery-confirm-v3.3.4/jquery-confirm.min.css' %}">
    <script src="{% static 'lib/jquery-confirm-v3.3.4/jquery-confirm.min.js' %}"></script>
    <!-- My css -->
    <link rel="stylesheet" href="{% static 'css/mystyle.css' %}">
    <!-- Functions -->
    <script src="{% static 'js/functions.js' %}"></script>
    <!-- Block head -->
    {% block head %} {% endblock %}
</head>
{% block body %} {% endblock %}

</html>

app/templates/layout.html
{% extends 'vtc/body.html' %}

app/templates/list.html
{% extends 'layout.html' %} {% load static %} {% block head %}
<link rel="stylesheet" href="{% static 'lib/datatables-1.10.20/css/dataTables.bootstrap4.min.css' %}" />
<link rel="stylesheet" href="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/css/responsive.bootstrap4.min.css' %}" />
<script src="{% static 'lib/datatables-1.10.20/js/jquery.dataTables.js' %}"></script>
<script src="{% static 'lib/datatables-1.10.20/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/js/responsive.bootstrap4.min.js' %}"></script>

{% block head_list %} {% endblock %} {% endblock %} {% block content %}
<div class="card card-primary">
    <div class="card-header" style="background-color: rgba( 9, 54, 115 );">
        <h3 class="card-title">
            <i class="fas fa-search"></i> {{ title }}
        </h3>
    </div>
    <div class="card-body">
        <table class="table table-bordered" id="data">
            <thead>
                {% block columns %} {% endblock %}
            </thead>
            <tbody>
                {% block rows %} {% endblock %}
            </tbody>
        </table>
    </div>
    <div class="card-footer">
        {% block buttons_list %}
        <a href="{{ create_url }}" class="btn btn-primary btn-flat btnTest">
            <i class="fas fa-plus"></i> Nuevo registro
        </a>
        <a href="{{ list_url }}" class="btn btn-success btn-flat">
            <i class="fas fa-sync"></i> Actualizar
        </a>
        {% endblock %}
    </div>
</div>
{% endblock %} {% block javascript %}
<script type="application/javascript">
    $(function() {
        $('#data').DataTable({
            responsive: true,
            autoWidth: false
        });

        $('.btnTest').on('click', function() {
            $.ajax({
                url: '{% url "erp:category_list" %}',
                type: 'POST',
                data: {
                    id: 1
                },
                dataType: 'json'
            }).done(function(data) {
                console.log(data);
            }).fail(function(jqXHR, textStatus, errorThrown) {
                alert(textStatus + ': ' + errorThrown);
            }).always(function(data) {

            });
        });
    });
</script>
{% endblock %}

app/templates/tests.html
{% extends 'layout.html' %}
{% load widget_tweaks %}
{% load static %}
{% block head %}
    <link href="{% static 'lib/jquery-ui-1.12.1/jquery-ui.min.css' %}" rel="stylesheet"/>
    <script src="{% static 'lib/jquery-ui-1.12.1/jquery-ui.min.js' %}"></script>

    <link href="{% static 'lib/select2-4.0.13/css/select2.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'lib/select2-4.0.13/css/select2-bootstrap4.min.css' %}" rel="stylesheet"/>
    <script src="{% static 'lib/select2-4.0.13/js/select2.min.js' %}"></script>
    <script src="{% static 'lib/select2-4.0.13/js/i18n/es.js' %}"></script>
{% endblock %}
{% block content %}
    <form method="post" action="." enctype="multipart/form-data">
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">
                    <i class="fas fa-plus"></i>
                    {{ title }}
                </h3>
            </div>
            <div class="card-body">
                <div class="form-group">
                    <label>Categorias:</label>
                    {{ form.categories }}
                </div>
                <div class="form-group">
                    <label>Productos:</label>
                    {{ form.products }}
                </div>
                <div class="form-group">
                    <label>Buscador:</label>
                    {{ form.search }}
                </div>
            </div>
        </div>
    </form>
    <script>
        var select_products = $('select[name="products"]');
        $(function () {

            $('.select2').select2({
                theme: "bootstrap4",
                language: 'es'
            });

            $('select[name="categories"]').on('change', function () {
                var id = $(this).val();
                var options = '<option value="">--------------------</option>';
                if (id === '') {
                    select_products.html(options);
                    return false;
                }
                $.ajax({
                    url: window.location.pathname,
                    type: 'POST',
                    data: {
                        'action': 'search_product_id',
                        'id': id
                    },
                    dataType: 'json',
                }).done(function (data) {
                    if (!data.hasOwnProperty('error')) {
                        select_products.html('').select2({
                            theme: "bootstrap4",
                            language: 'es',
                            data: data
                        });
                        /*$.each(data, function (key, value) {
                            options += '<option value="' + value.id + '">' + value.name + '</option>';
                        });*/
                        return false;
                    }
                    message_error(data.error);
                }).fail(function (jqXHR, textStatus, errorThrown) {
                    alert(textStatus + ': ' + errorThrown);
                }).always(function (data) {
                    //select_products.html(options);
                });
            });

            select_products.on('change', function () {
                var value = select_products.select2('data')[0];
                console.log(value);
            });

            var availableTags = [
                "ActionScript",
                "AppleScript",
                "Asp",
                "BASIC",
                "C",
                "C++",
                "Clojure",
                "COBOL",
                "ColdFusion",
                "Erlang",
                "Fortran",
                "Groovy",
                "Haskell",
                "Java",
                "JavaScript",
                "Lisp",
                "Perl",
                "PHP",
                "Python",
                "Ruby",
                "Scala",
                "Scheme"
            ];

            $('input[name="search"]').autocomplete({
                source: function (request, response) {
                    $.ajax({
                        url: window.location.pathname,
                        type: 'POST',
                        data: {
                            'action': 'autocomplete',
                            'term': request.term
                        },
                        dataType: 'json',
                    }).done(function (data) {
                        response(data);
                    }).fail(function (jqXHR, textStatus, errorThrown) {
                        //alert(textStatus + ': ' + errorThrown);
                    }).always(function (data) {

                    });
                },
                delay: 500,
                minLength: 1,
                select: function (event, ui) {
                    console.log(ui.item);
                }
            });

            $('select[name="search"]').select2({
                theme: "bootstrap4",
                language: 'es',
                allowClear: true,
                ajax: {
                    delay: 250,
                    type: 'POST',
                    url: window.location.pathname,
                    data: function (params) {
                        var queryParameters = {
                            term: params.term,
                            action: 'autocomplete'
                        }
                        return queryParameters;
                    },
                    processResults: function (data) {
                        return {
                            results: data
                        };
                    },
                },
                placeholder: 'Ingrese una descripción',
                minimumInputLength: 1,
            });
        });
    </script>
{% endblock %}